# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'eyazis5-2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 900)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_browser = QtWidgets.QTextBrowser(self.centralwidget)
        self.text_browser.setObjectName("text_browser")
        self.verticalLayout.addWidget(self.text_browser)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1600, 20))
        self.menubar.setObjectName("menubar")
        self.menu_actions = QtWidgets.QMenu(self.menubar)
        self.menu_actions.setObjectName("menu_actions")
        # self.menu_settings = QtWidgets.QMenu(self.menu_actions)
        # self.menu_settings.setObjectName("menu_settings")
        # self.menu_language = QtWidgets.QMenu(self.menu_settings)
        # self.menu_language.setObjectName("menu_language")
        # self.menu_voice = QtWidgets.QMenu(self.menu_settings)
        # self.menu_voice.setObjectName("menu_voice")
        # self.menu_help = QtWidgets.QMenu(self.menubar)
        # self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.action_about = QtWidgets.QAction(MainWindow)
        self.action_about.setObjectName("actionAbout")
        # self.action_russian = QtWidgets.QAction(MainWindow)
        # self.action_russian.setObjectName("action_russian")
        # self.action_english = QtWidgets.QAction(MainWindow)
        # self.action_english.setObjectName("action_english")
        # self.action_female = QtWidgets.QAction(MainWindow)
        # self.action_female.setObjectName("action_female")
        # self.action_male = QtWidgets.QAction(MainWindow)
        # self.action_male.setObjectName("action_male")
        self.action_restart_sesion = QtWidgets.QAction(MainWindow)
        self.action_restart_sesion.setObjectName("action_restart_sesion")
        # self.menu_language.addAction(self.action_russian)
        # self.menu_language.addAction(self.action_english)
        # self.menu_voice.addAction(self.action_female)
        # self.menu_voice.addAction(self.action_male)
        # self.menu_settings.addAction(self.menu_voice.menuAction())
        # self.menu_settings.addAction(self.menu_language.menuAction())
        # self.menu_actions.addAction(self.menu_settings.menuAction())
        self.menu_actions.addAction(self.action_restart_sesion)
        # self.menu_help.addAction(self.action_about)
        # self.menubar.addAction(self.menu_actions.menuAction())
        # self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "VoiceAssistant"))
        self.text_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10.3pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p>\n"
"<p dir=\'rtl\' style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"></p></body></html>"))
        self.menu_actions.setTitle(_translate("MainWindow", "&Actions"))
        # self.menu_settings.setTitle(_translate("MainWindow", "&Settings"))
        # # self.menu_language.setTitle(_translate("MainWindow", "&Language"))
        # self.menu_voice.setTitle(_translate("MainWindow", "&Voice"))
        # self.menu_help.setTitle(_translate("MainWindow", "&Help"))
        # self.action_about.setText(_translate("MainWindow", "&About"))
        # # self.action_russian.setText(_translate("MainWindow", "&Russian"))
        # # self.action_english.setText(_translate("MainWindow", "&English"))
        # self.action_female.setText(_translate("MainWindow", "&Female"))
        # self.action_male.setText(_translate("MainWindow", "&Male"))
        self.action_restart_sesion.setText(_translate("MainWindow", "&Clear"))
